on: 
  workflow_dispatch:
    inputs:
      revision_new:
        description: 'Revision New'     
        required: true
      revision_current:
        description: 'Revision Current'     
        # required: true
      # tags:
        # description: 'Test scenario tags'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.revision_new }}"