on:
  push:
    branches:
      - main

jobs:
  mockJob:
    name: Run terraform with 0 traffic
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Merged into main"
  # terraformBit:
  #   - uses: hashicorp/setup-terraform@v1

  #   - run: terraform init

  #   - id: plan
  #     run: terraform plan -no-color

  #   - run: echo ${{ steps.plan.outputs.stdout }}
  #   - run: echo ${{ steps.plan.outputs.stderr }}
  #   - run: echo ${{ steps.plan.outputs.exitcode }}